# Generated by Django 5.2.7 on 2025-11-12 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_end_date_remove_project_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('Zone_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name_zone', models.CharField(max_length=100)),
                ('coords_polys', models.JSONField(blank=True, null=True)),
                ('description_zone', models.TextField(blank=True, null=True)),
                ('name_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('cam_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name_cam', models.CharField(max_length=100)),
                ('coords_cam', models.JSONField(blank=True, null=True)),
                ('adresse_cam', models.GenericIPAddressField(blank=True, null=True)),
                ('num_port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('rest_de_path', models.CharField(blank=True, max_length=200, null=True)),
                ('description_cam', models.TextField(blank=True, null=True)),
                ('custom_url', models.TextField(blank=True, null=True)),
                ('is_full_rtsp_url', models.BooleanField(default=False)),
                ('name_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='projects.zone')),
            ],
        ),
    ]
