# Generated by Django 5.2.7 on 2025-11-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='badge_number',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='department',
        ),
    ]
